nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  dojocode:
    npmAlwaysAuth: true
    npmAuthToken: "${VERDACCIO_TOKEN}"
    npmRegistryServer: "https://registry.springtech.co/"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
